Implement full NK1 segment
ruby-hl7/ruby-hl7 pull request #125
Opened 2023-10-27 01:56 UTC by doconnor-clintel

https://hl7-definition.caristix.com/v2/HL7v2.3.1/Segments/NK1

2023-11-02 20:12 UTC, Stratus3D commented
Hi @doconnor-clintel , thanks for the PR! I don't really maintain this project anymore. @ruby-hl7/maintainers can someone take a look?

2024-11-06 13:55 UTC, LucasMontorio requested changes
Hi! 
I know that this PR is quite old but I'm here to help with it :)

I have 3 main comments: 
- I suggest that we support the latest NK1 segment spec as defined in Caristix [here](https://hl7-definition.caristix.com/v2/HL7v2.3.1/Segments/NK1)
- This new segment requires specific specs using the newly-introduced fields
- The `TODO` introduced here could be implemented directly




I suggest that we support the latest NK1 segment spec as defined in Caristix [here](https://hl7-definition.caristix.com/v2/HL7v2.3.1/Segments/NK1)

2024-11-06 13:55 UTC, LucasMontorio commented on lib/segments/nk1.rb
> +  add_field :sex # TODO: raise HL7::InvalidDataError.new( "bad administrative sex value (not F|M|O|U|A|N|C)" ) ?
**todo:** Why not doing it in the PR directly? :)

2024-11-27 16:44 UTC, LucasMontorio commented
Segment implemented in this PR: https://github.com/ruby-hl7/ruby-hl7/pull/142

2024-11-27 16:44 UTC, closed without merging